apiVersion: v1
kind: Service
metadata:
  labels:
    component: ratelimit
    project: demo
  name: ratelimit-service
  namespace: ratelimit
spec:
  ports:
  - name: port1
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    component: "ratelimit"
    project: "demo"
  sessionAffinity: None
  type: ClusterIP

