apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: ratelimit-upstream
  namespace: ratelimit
spec:
  kube:
    selector:
      project: demo
    serviceName: ratelimit-service
    serviceNamespace: ratelimit
    servicePort: 8081

